### ISSUE TITLE
errorx redeme

### ISSUE THREAD

**Issue by veeding** [vesoft-inc/go-pkg#22]
<img width="994" alt="image" src="https://user-images.githubusercontent.com/104374143/178685076-175349cd-72d2-444f-809a-00ee8a7c6252.png">

In this [redeme](https://github.com/vesoft-inc/go-pkg/tree/master/errorx),
the code length should be 8. For example, 40000000.

**Comment by veezhang** [comment]
fixed: #23

**Comment by veezhang** [comment]
done
